<a href="https://colab.research.google.com/github/AishwaryaKyasari/Datascience/blob/main/IRIS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
from sklearn.datasets import load_iris
iris_data=load_iris()

# The whole Data set was splitted or classified into features and target

where features conatins -> sepal_length,speal_width,petal_length and petal_width

and target contains values 0- setosa 1-versicolor and 2-verginica|

In [25]:
iris_features=iris_data.data
iris_target=iris_data.target

In [26]:
iris_data.feature_names # it is displaying the first row

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [27]:
iris_data.target_names # it is displaying the first column

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [28]:
iris_features.shape

(150, 4)

In [29]:
iris_target.shape

(150,)

## Aplying Machine Learning algorithm
# LogisticRegression

In [30]:
#importing cross validation score
from sklearn.model_selection import cross_val_score

In [31]:
#logistic Regression is present in sklearn lib
from sklearn.linear_model import LogisticRegression
lr_model=LogisticRegression() #calling the method
lr_score=cross_val_score(lr_model,iris_features,iris_target,cv=3)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


Cross_val_score is a method which runs cross validation on a dataset to test whether the model can generalise over the whole dataset. The function returns a list of one score per split, and the average of these scores can be calculated to provide a single metric value for the dataset. This is a function and a technique which you should add to your workflow to make sure you are developing highly performant models.

In [32]:
lr_score

array([0.98, 0.96, 0.98])

In [33]:
import numpy as np
avg_val=np.average(lr_score)
avg_val

0.9733333333333333

In [36]:
from sklearn.ensemble import RandomForestClassifier
rf_model= RandomForestClassifier() #Creating an instacnce of RandomForestClassifier
rf_score=cross_val_score(rf_model,iris_features,iris_target,cv=3)

In [37]:
rf_score

array([0.98, 0.94, 0.96])

In [38]:
avg_random=np.average(rf_score)
avg_random

0.96

In [45]:
from sklearn.svm import SVC
svm_model = SVC()# creating an instance of svm model
rf_svc=cross_val_score(svm_model,iris_features,iris_target,cv=3)

In [47]:
rf_svc

array([0.96, 0.98, 0.94])

In [48]:
avg_svc=np.average(rf_svc)
avg_svc

0.96

In [49]:
model_comparision = {" Model ":["Logistic Regression","Random Forest","Support Vector Machine"],
" 3-fold Cross validation score ":[lr_score,rf_score,rf_svc],
" Average Score ":[avg_val,avg_random,avg_svc]}

In [51]:
import pandas as pd
model_comp=pd.DataFrame(model_comparision)
model_comp

Model   3-fold Cross validation score    Average Score 
0     Logistic Regression              [0.98, 0.96, 0.98]         0.973333
1           Random Forest              [0.98, 0.94, 0.96]         0.960000
2  Support Vector Machine              [0.96, 0.98, 0.94]         0.960000

In [53]:
lr_model.fit(iris_features,iris_target,3)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [54]:
ypred=lr_model.predict(iris_features)

In [55]:
np.sum(ypred!=iris_target)

2

In [56]:
print(iris_data.target_names[lr_model.predict([[4.5,4.5,5.8,3.5]])])

['virginica']
